name = "uv-k5-repeater-web"
compatibility_date = "2026-08-01"
pages_build_output_dir = "dist"

[vars]
PUBLIC_SITE_URL = "https://repeater.mizuki.top"

[[d1_databases]]
binding = "DB"
database_name = "mizuki-repeater"
database_id = "a983d7c4-6501-4157-8839-7fbcbe00f1af"
